require("neo-tree").setup({
        close_if_last_window = false,
        popup_border_style = "rounded",
        enable_git_status = true,
        enable_diagnostics = true,
        default_component_configs = {
                indent = {
                        indent_size = 2,
                        padding = 1,
                        with_markers = true,
                        indent_marker = "│",
                        last_indent_marker = "└",
                        highlight = "NeoTreeIndentMarker",
                },
                icon = {
                        folder_closed   = " ",
                        folder_open     = " ",
                        folder_empty    = "󰉖 ",
                        default         = " ",
                },
                git_status = {
                        symbols = {
                                added           = " ",
                                modified        = "",
                                deleted         = " ",
                                renamed         = "➜",
                                untracked       = "★ ",
                                ignored         = "◌ ",
                                unstaged        = "✗ ",
                                staged          = "✓ ",
                                conflict        = " ",
                        },
                },
                -- git_status = {
                --         symbols = {
                --                 added    = "✚ ",
                --                 modified = " ",
                --                 deleted  = "✖ ",
                --                 renamed  = "➜ ",
                --                 untracked = " ",
                --                 ignored  = "◌ ",
                --                 unstaged = "✗ ",
                --                 staged   = "✓ ",
                --                 conflict = " ",
                --         },
                -- },
        },
        window = {
                width = 30,
                mappings = {
                        ["<CR>"] = "open",
                        ["o"] = "open",
                        ["l"] = "open",
                        ---- ["h"] = "close_node", -------------------------------------------------
                        ["h"] = "navigate_up",
                        ["a"] = "add",
                        ["d"] = "delete",
                        ["r"] = "rename",
                        ["y"] = "copy_to_clipboard",
                        ["x"] = "cut_to_clipboard",
                        ["p"] = "paste_from_clipboard",
                        ["c"] = "copy",
                        ["m"] = "move",
                        ["q"] = "close_window",
                        ["R"] = "refresh",
                        ["?"] = "show_help",
                },
        },
})
