local km = vim.keymap.set
local smart_splits = require('smart-splits')

---------------------- Leader键 ----------------------
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

km('n', '<leader>w', ':w<CR>',                  { desc = 'Write' })
km('n', '<leader>q', ':q<CR>',                  { desc = 'Quit' })
km('n', '<leader>h', '0',                       { desc = 'Go to start of line' })
km('n', '<leader>l', '$',                       { desc = 'Go to end of line' })
km('n', '<leader>k', 'gg',                      { desc = 'Go to top of file' })
km('n', '<leader>j', 'G',                       { desc = 'Go to bottom of file' })
km('n', '<leader>e', '<cmd>Neotree toggle<CR>', { desc = 'Toggle Neo-tree' })
km("n", "<leader>sh", smart_splits.swap_buf_left,  { desc = "与左侧窗口交换内容" })
km("n", "<leader>sj", smart_splits.swap_buf_down,  { desc = "与下方窗口交换内容" })
km("n", "<leader>sk", smart_splits.swap_buf_up,    { desc = "与上方窗口交换内容" })
km("n", "<leader>sl", smart_splits.swap_buf_right, { desc = "与右侧窗口交换内容" })
km("n", "<leader>sv", "<C-w>v",                 { desc = "垂直分屏" })
km("n", "<leader>sh", "<C-w>s",                 { desc = "水平分屏" })
km("n", "<leader>se", "<C-w>=",                 { desc = "使所有窗口等宽等高" })
km("n", "<leader>sx", "<C-w>c",                 { desc = "关闭当前窗口" })
km("n", "<leader>ff", "<cmd>Telescope find_files<CR>",  { desc = "查找文件" })
km("n", "<leader>fg", "<cmd>Telescope live_grep<CR>",   { desc = "全文搜索" })
km("n", "<leader>fb", "<cmd>Telescope buffers<CR>",     { desc = "切换缓冲区" })
km("n", "<leader>fh", "<cmd>Telescope help_tags<CR>",   { desc = "帮助标签" })
km("n", "<leader>b", ":lua require('bufswi').open()<CR>", { desc = "打开缓冲区切换器" })
km("n", "<leader>rr", ":RunCode<CR>",                   { desc = "根据文件类型运行代码" })
km("n", "<leader>rf", ":RunFile<CR>",                   { desc = "运行当前文件" })
km("n", "<leader>rp", ":RunProject<CR>",                { desc = "运行当前项目" })
km("n", "<leader>rc", ":RunClose<CR>",                  { desc = "关闭运行窗口" })
-- km('n', '<leader>fq', _G.toggle_qf,                     { desc = '切换 Quickfix 窗口' })

km('n', '-', '<cmd>Oil<CR>',                    { desc = 'Open parent directory with Oil' })
km("n", "<C-h>", smart_splits.move_cursor_left, { desc = "移动到左侧窗口/面板" })
km("n", "<C-j>", smart_splits.move_cursor_down, { desc = "移动到下方窗口/面板" })
km("n", "<C-k>", smart_splits.move_cursor_up,   { desc = "移动到上方窗口/面板" })
km("n", "<C-l>", smart_splits.move_cursor_right,{ desc = "移动到右侧窗口/面板" })
km("n", "<A-S-k>", smart_splits.resize_up,      { desc = "增加窗口高度" })
km("n", "<A-S-j>", smart_splits.resize_down,    { desc = "减小窗口高度" })
km("n", "<A-S-h>", smart_splits.resize_left,    { desc = "减小窗口宽度" })
km("n", "<A-S-l>", smart_splits.resize_right,   { desc = "增加窗口宽度" })
