local km = vim.keymap.set
local splt = require('smart-splits')

---------------------- Leader键 ----------------------
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

km('n', '<leader>w', ':w<CR>',                          { desc = 'Write' })
km('n', '<leader>q', ':q<CR>',                          { desc = 'Quit' })
km('n', '<leader>h', '0',                               { desc = '跳转至行首' })
km('n', '<leader>l', '$',                               { desc = '跳转至行尾' })
km('n', '<leader>k', 'gg',                              { desc = '跳转至文件首' })
km('n', '<leader>j', 'G',                               { desc = '跳转至文件尾' })
km('n', '<leader>e', '<cmd>Neotree toggle<CR>',         { desc = '切换 Neo-tree 显示状态' })
km('n', '<leader>nh','<cmd>nohl<CR>',                   { desc = '取消高亮' })
km('n', '<leader>sh', splt.swap_buf_left,               { desc = '与左侧窗口交换内容' })
km('n', '<leader>sj', splt.swap_buf_down,               { desc = '与下方窗口交换内容' })
km('n', '<leader>sk', splt.swap_buf_up,                 { desc = '与上方窗口交换内容' })
km('n', '<leader>sl', splt.swap_buf_right,              { desc = '与右侧窗口交换内容' })
km('n', '<leader>sv', '<C-w>v',                         { desc = '垂直分屏' })
km('n', '<leader>sh', '<C-w>s',                         { desc = '水平分屏' })
km('n', '<leader>se', '<C-w>=',                         { desc = '使所有窗口等宽等高' })
km('n', '<leader>sx', '<C-w>c',                         { desc = '关闭当前窗口' })
km('n', '<leader>ff', '<cmd>Telescope find_files<CR>',          { desc = '查找文件' })
km('n', '<leader>fg', '<cmd>Telescope live_grep<CR>',           { desc = '全文搜索' })
km('n', '<leader>fb', '<cmd>Telescope buffers<CR>',             { desc = '切换缓冲区' })
km('n', '<leader>fh', '<cmd>Telescope help_tags<CR>',           { desc = '帮助标签' })
km('n', '<leader>bb', ':lua require("bufswi").open()<CR>',      { desc = '打开缓冲区切换器' })
km('n', '<leader>rr', ':RunCode<CR>',                   { desc = '根据文件类型运行代码' })
km('n', '<leader>rf', ':RunFile<CR>',                   { desc = '运行当前文件' })
km('n', '<leader>rp', ':RunProject<CR>',                { desc = '运行当前项目' })
km('n', '<leader>rc', ':RunClose<CR>',                  { desc = '关闭运行窗口' })
km('n', '<leader>gn', ':tabnew<CR>',                    { desc = '新建标签页' })
km('n', '<leader>gq', ':tabclose<CR>',                  { desc = '关闭当前标签页' })
km('n', '<leader>gh', 'gT',                             { desc = '切换到前一个标签页' })
km('n', '<leader>gl', 'gt',                             { desc = '切换到后一个标签页' })
km('n', '<leader>fq', _G.toggle_qf,                     { desc = '切换 Quickfix 窗口开关状态' })


km('n', '-', '<cmd>Oil<CR>',                            { desc = '使用 Oil 打开当前目录' })
km('n', '<A-j>', ':m .+1<CR>==',                { noremap = true, desc = 'Move line down' })
km('n', '<A-k>', ':m .-2<CR>==',                { noremap = true, desc = 'Move line up' })
km('v', '<A-j>', ":m '>+1<CR>gv=gv",            { noremap = true, desc = 'Move selected lines down' })
km('v', '<A-k>', ":m '<-2<CR>gv=gv",            { noremap = true, desc = 'Move selected lines up' })
km('n', '<C-h>', splt.move_cursor_left,                 { desc = '移动到左侧窗口/面板' })
km('n', '<C-j>', splt.move_cursor_down,                 { desc = '移动到下方窗口/面板' })
km('n', '<C-k>', splt.move_cursor_up,                   { desc = '移动到上方窗口/面板' })
km('n', '<C-l>', splt.move_cursor_right,                { desc = '移动到右侧窗口/面板' })
km('n', '<A-S-k>', splt.resize_up,                      { desc = '增加窗口高度' })
km('n', '<A-S-j>', splt.resize_down,                    { desc = '减小窗口高度' })
km('n', '<A-S-h>', splt.resize_left,                    { desc = '减小窗口宽度' })
km('n', '<A-S-l>', splt.resize_right,                   { desc = '增加窗口宽度' })
